name: equibind
channels:
  - conda-forge
  - defaults
  - dglteam
  - pytorch
dependencies:
  - python=3.7
  - pytorch 1.10
  - torchvision
  - cudatoolkit=11.7
  - torchaudio
  - dgl-cuda11.7
  - rdkit
  - openbabel
  - biopython
  - rdkit
  - biopandas
  - pot
  - dgllife
  - joblib
  - pyaml
  - icecream
  - matplotlib
  - tensorboard
  - psutil
  - libgcc



